#!/bin/bash
echo "📱 Capturing iOS errors..."
echo "Run this while your iOS app is running to capture console errors"
echo ""
echo "Method 1: Metro Bundler Console"
echo "  - Check the terminal where 'npx expo start' is running"
echo "  - Look for red error messages"
echo ""
echo "Method 2: React Native Logs"
echo "  npx react-native log-ios"
echo ""
echo "Method 3: Xcode Console"
echo "  - Open Xcode"
echo "  - Run the app from Xcode"
echo "  - Check the console output at the bottom"
echo ""
echo "Method 4: iOS Simulator Console"
echo "  - Open Simulator"
echo "  - Device > Console (or Cmd+/)"
echo ""
echo "Please copy the error messages and share them."
